<br/>

# An implementation of <strong>Dabbaghian & Wu's algorithm</strong> of constructing non-cyclic pandiagonal Latin squares for the order 13
<br/>

#### the algorithm from:
### Dabbaghian V, Wu T. Constructing non-cyclic pandiagonal Latin squares of prime orders. <em>Journal of Discrete Algorithms</em>. 2015;30:70–7.
https://doi.org/10.1016/j.jda.2014.12.001
<br/>
<br/>
#### The implementation was inspired by N.V. Makarova 2021
https://doi.org/10.5281/zenodo.4695879
<br/>
<br/>

In [5]:
import numpy as np

In [6]:
a_b = ((1,4),(1,10),(2,7),(2,8),(3,4),(3,12),(5,7),(5,11),(6,8),(6,11),(9,10),(9,12))
u = (4, 9, 1, 12, 1, 12)
lam1 = ( lambda a, b: (b - a) % 13,
        lambda a, b: (a - b) % 13,
        lambda a, b: (a + b) % 13,
        lambda a, b: (a + b) % 13,
        lambda a, b: (- b) % 13,
        lambda a, b: b % 13,
        lambda a, b: (a ** 2) % 13
       )
lam2 = ( lambda a, b, i: ((a + b) * i) % 13,
        lambda a, b, i: ((a + b) * i) % 13,
        lambda a, b, i: ((b - a) * i) % 13,
        lambda a, b, i: ((a - b) * i) % 13,
        lambda a, b, i: (a * i) % 13,
        lambda a, b, i: (a * i) % 13,
        lambda a, b, i: ((a + b) * i) % 13
       )


def findLam(a: int, b: int, j: int) -> int:
    for i in range(13):
        if lam1[j](a, b) == lam2[j](a, b, i):
            return i
    raise Exception('Failure to find lambda_L for j %d' % j)

    
def buildSquare(lam: int) -> np.ndarray:
    matrix = np.zeros((13, 13),dtype='int')
    for i in range(13):
        for j in range(13):
            matrix[i,j] = (lam * i + j) % 13
    return matrix


def shift(m: np.ndarray, u: int, a: int, b: int) -> None:
    l = findLam(a=a, b=b, j=6)
    for i in range(13):
        m[i, (i*u+a)%13], m[i, (i*u)%13], m[i, (i*u+b)%13], m[i, (i*u+b+l)%13], m[i, (i*u+l)%13], m[i, (i*u+l+b-a)%13] = m[i, (i*u)%13], m[i, (i*u+b)%13], m[i, (i*u+a)%13],  m[i, (i*u+l)%13], m[i, (i*u+b-a+l)%13], m[i, (i*u+b+l)%13]


def pandiagonal(matrix: np.ndarray) -> bool:
    matrix_ = matrix.copy()
    for i in range(1,13):
        matrix_[i,:] = matrix_[i,np.mod(np.arange(13) + i, 13)]
    for i in range(13):
        if np.unique(matrix[:,i]).size < 13:
            print(np.unique(matrix[:,i]).size)
            return False
    matrix_ = matrix.copy()
    for i in range(1,13):
        matrix_[i,:] = matrix_[i,np.mod(np.arange(13) - i, 13)]
    for i in range(13):
        if np.unique(matrix[:,i]).size < 13:
            print(np.unique(matrix[:,i]).size)
            return False
    return True

In [7]:
for n in range(12):
    for k in range(6):
        lamL = findLam(*a_b[n], k)
        square = buildSquare(lamL)
        shift(square, u[k], *a_b[n])
        if(pandiagonal(square)):
            print('\n********************************************\n\tThe pandiagonal Latin square\n********************************************\n')
            print(square)
        else:
            print('\n++++++++++++++++++++++++++++++++++++++++++++\n\tTHE NON-PANDIAGONAL LATIN SQUARE\n++++++++++++++++++++++++++++++++++++++++++++\n')
            print(square)
            



********************************************
	The pandiagonal Latin square
********************************************

[[ 4  0  2  3  1  5  6  7 11  9 10 12  8]
 [11 12  1 10  6  2  4  5  3  7  8  9  0]
 [ 9 10 11  2  0  1  3 12  8  4  6  7  5]
 [ 6  8  9  7 11 12  0  4  2  3  5  1 10]
 [ 5  7  3 12  8 10 11  9  0  1  2  6  4]
 [ 3  4  8  6  7  9  5  1 10 12  0 11  2]
 [ 1  2  0  4  5  6 10  8  9 11  7  3 12]
 [ 0  9  5  1  3  4  2  6  7  8 12 10 11]
 [10  1 12  0  2 11  7  3  5  6  4  8  9]
 [ 8  6 10 11 12  3  1  2  4  0  9  5  7]
 [ 2 11  7  9 10  8 12  0  1  5  3  4  6]
 [ 7  5  6  8  4  0  9 11 12 10  1  2  3]
 [12  3  4  5  9  7  8 10  6  2 11  0  1]]

********************************************
	The pandiagonal Latin square
********************************************

[[ 4  0  2  3  1  5  6  7 11  9 10 12  8]
 [12  3  4  5  9  7  8 10  6  2 11  0  1]
 [ 7  5  6  8  4  0  9 11 12 10  1  2  3]
 [ 2 11  7  9 10  8 12  0  1  5  3  4  6]
 [ 8  6 10 11 12  3  1  2  4  0  9  5  7]

<br/>
<br/>
<br/>
<br/>
<br/>
<br/>

##### © 2021 ipgmvq
##### GPL-3.0 License